#!/bin/sh
#####################
# Zeta OS Base Init #
########################
# Author : Abe Hoffman #
# Date   : 10-26-2018  #
##################################################################
# Description : This script acts as PID1 immediately after the   #
#               initramfs is unpacked. Its sole purpose is to    #
#               (perform as little work as possible) then hand-  #
#               off control of PID1 to the next script,          #
#               /sbin/init where the main userland boot-time     #
#               work is done.                                    #
##################################################################

#dmesg -n 1
#mount -t devtmpfs none /dev
#mount -t proc none /proc
#mount -t sysfs none /sys

dmesg -n 1
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t tmpfs none /tmp -o mode=1777
mount -t sysfs none /sys
mkdir -p /dev/pts
mount -t devpts none /dev/pts
setsid cttyhack /bin/sh

#mount -t tmpfs none /mnt
#mkdir /mnt/dev
#mkdir /mnt/sys
#mkdir /mnt/proc
##mkdir /mnt/tmp
#mount --move /dev /mnt/dev
#mount --move /sys /mnt/sys
#mount --move /proc /mnt/proc
##mount --move /tmp /mnt/tmp
#exec switch_root /mnt /etc/main_init.sh


#setsid cttyhack /bin/sh
#exec /sbin/init


## Core init commands
#/etc/init.sh
## Filesystem and Main init
#exec /etc/filesystem.sh
