#!/bin/sh
#####################
# Zeta OS Base Init #
########################
# Author : Abe Hoffman #
# Date   : 10-26-2018  #
##################################################################
# Description : This script acts as PID1 immediately after the   #
#               initramfs is unpacked. Its sole purpose is to    #
#               (perform as little work as possible) then hand-  #
#               off control of PID1 to the next script,          #
#               /sbin/init where the main userland boot-time     #
#               work is done.                                    #
##################################################################

# Core init commands
/etc/init.sh
# Filesystem and Main init
exec /etc/filesystem.sh
