#!/bin/sh
#####################
# Zeta OS Base Init #
########################
# Author : Abe Hoffman #
# Date   : 10-26-2018  #
##################################################################
# Description : This script creates PID1. It first populates the #
#               device tree, by using the kernel's nuilt-in udev #
#               tooling. Then it populates the virtual           #
#               filesystems and finally triggers the ash shell   #
#               (which is just BusyBox).                         #
##################################################################

# Only critical kernel messages printed to the console (dmesg shows everything)
dmesg -n 1
# Prepare auto-udev, system hooks and virtual filesystems
mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys
mount -n -t tmpfs    tmpfs    /x
# Clear the screen and show Message of the Day
clear;cat /etc/motd
# Hand the (ash) shell over to the user
setsid cttyhack /bin/sh
