#!/bin/sh
#####################
# Zeta OS User Init #
########################
# Author : Abe Hoffman #
# Date   : 10-26-2018  #
##################################################################
# Description : This script acts as PID1 immediately after /init #
#               passes control to it.                            #
##################################################################

## # Test if /proc/cmdline is a regular file. Otherwise, mount proc.
## [ -f /proc/cmdline ] || /bin/mount /proc
## 
## # Remount rootfs rw
## /bin/mount -o remount,rw /
## 
## # Mount system devices from /etc/fstab
## /bin/mount -a
## 
## clear
## 
## /etc/init.d/tc-config
